server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: ai-role-playing-system
  
  # Spring AI DashScope (通义千问) 配置
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-turbo  # 可选: qwen-turbo, qwen-plus, qwen-max
          temperature: 0.7
          max-tokens: 2000
          top-p: 0.8

# 阿里云语音服务配置
alibaba:
  cloud:
    access-key-id: ${ALIBABA_ACCESS_KEY_ID}
    access-key-secret: ${ALIBABA_ACCESS_KEY_SECRET}
    
    # ASR (语音识别) 配置
    asr:
      app-key: ${ALIBABA_ASR_APP_KEY}
      url: wss://nls-gateway.cn-shanghai.aliyuncs.com/ws/v1
      format: pcm
      sample-rate: 16000
      enable-intermediate-result: true
      enable-punctuation-prediction: true
      enable-inverse-text-normalization: true
      
    # TTS (语音合成) 配置  
    tts:
      app-key: ${ALIBABA_TTS_APP_KEY}
      url: wss://nls-gateway.cn-shanghai.aliyuncs.com/ws/v1
      format: wav
      sample-rate: 16000
      voice: siqi  # 默认发音人，可根据角色切换

# WebSocket 配置
websocket:
  path: /ws/voice-chat
  allowed-origins: "*"  # 生产环境请设置具体域名
  max-session-idle-timeout: 300000  # 5分钟
  max-text-message-buffer-size: 8192
  max-binary-message-buffer-size: 65536

# 角色配置
character:
  profiles:
    default:
      name: "智能助手"
      personality: "你是一个友善、专业的AI助手，能够帮助用户解决各种问题。"
      voice: "siqi"
    anime-girl:
      name: "萌妹子小爱"
      personality: "你是一个可爱活泼的二次元少女，说话带有萌萌的语气，喜欢用'呢'、'哦'等语气词。"
      voice: "aixia"
    professional:
      name: "专业顾问"
      personality: "你是一个严谨专业的商务顾问，说话简洁明了，注重效率和准确性。"
      voice: "zhiyu"

# 日志配置
logging:
  level:
    com.example.airoleplaying: DEBUG
    org.springframework.ai: DEBUG
    com.alibaba.nls: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/ai-role-playing.log
    max-size: 10MB
    max-history: 30

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
